# Generated by Django 5.0.1 on 2024-01-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rating', models.FloatField()),
                ('type', models.TextField()),
                ('language', models.TextField()),
                ('category', models.TextField()),
                ('duration', models.TextField()),
                ('certificate', models.TextField()),
                ('date', models.DateField()),
                ('banner', models.ImageField(upload_to='todoimage')),
                ('poster', models.ImageField(upload_to='todoimage')),
            ],
        ),
    ]
